The Dart VM service is listening on http://127.0.0.1:57000/ynkvvWUlKVc=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:57000/ynkvvWUlKVc=/devtools?uri=ws://127.0.0.1:57000/ynkvvWUlKVc=/ws
The Dart VM service is listening on http://127.0.0.1:57183/jWravQd2t08=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:57183/jWravQd2t08=/devtools?uri=ws://127.0.0.1:57183/jWravQd2t08=/ws
The Dart VM service is listening on http://127.0.0.1:57451/C5Egpjat7FA=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:57451/C5Egpjat7FA=/devtools?uri=ws://127.0.0.1:57451/C5Egpjat7FA=/ws
The Dart VM service is listening on http://127.0.0.1:57626/hndCDbV1tKU=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:57626/hndCDbV1tKU=/devtools?uri=ws://127.0.0.1:57626/hndCDbV1tKU=/ws
The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unable to find the context to /Users/pavlovsky/.pub-cache/hosted/pub.dev/custom_lint_core-0.5.0/lib/src/fixes.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:143:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:406:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:564:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:267:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:261:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:238:22)
<asynchronous suspension>
#4      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:177:17)
<asynchronous suspension>
#5      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#6      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unable to find the context to /Users/pavlovsky/.pub-cache/hosted/pub.dev/custom_lint_core-0.5.0/lib/src/fixes.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:143:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:406:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:564:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:267:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:261:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:238:22)
<asynchronous suspension>
#4      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:177:17)
<asynchronous suspension>
#5      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#6      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unable to find the context to /Users/pavlovsky/.pub-cache/hosted/pub.dev/custom_lint_core-0.5.0/lib/src/fixes.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:143:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:406:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:564:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:267:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:261:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:238:22)
<asynchronous suspension>
#4      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:177:17)
<asynchronous suspension>
#5      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#6      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

The Dart VM service is listening on http://127.0.0.1:57889/6J6-MtnCLUc=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:57889/6J6-MtnCLUc=/devtools?uri=ws://127.0.0.1:57889/6J6-MtnCLUc=/ws
The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unable to find the context to /Users/pavlovsky/.pub-cache/hosted/pub.dev/analyzer-5.12.0/lib/source/source_range.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:143:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:406:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:564:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:267:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:261:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:238:22)
<asynchronous suspension>
#4      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:177:17)
<asynchronous suspension>
#5      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#6      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

The Dart VM service is listening on http://127.0.0.1:58284/ahhp4l9AHxQ=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:58284/ahhp4l9AHxQ=/devtools?uri=ws://127.0.0.1:58284/ahhp4l9AHxQ=/ws
The Dart VM service is listening on http://127.0.0.1:58831/k3GbcNpiSUs=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:58831/k3GbcNpiSUs=/devtools?uri=ws://127.0.0.1:58831/k3GbcNpiSUs=/ws
The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unable to find the context to /Users/pavlovsky/.pub-cache/hosted/pub.dev/custom_lint_core-0.5.0/lib/src/change_reporter.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:143:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:406:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:564:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:267:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:261:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:238:22)
<asynchronous suspension>
#4      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:177:17)
<asynchronous suspension>
#5      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#6      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

